"""Backfilling

Revision ID: 26f7e4f33872
Revises: bac8378b87ff
Create Date: 2026-09-18 15:27:22.131808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f7e4f33872'
down_revision: Union[str, Sequence[str], None] = 'bac8378b87ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    conn = op.get_bind()

    req_id = conn.execute(sa.text("SELECT id FROM users WHERE role = 'ADMIN' ORDER BY id ASC LIMIT 1")).scalar()

    if req_id is not None:
        conn.execute(sa.text("UPDATE categories SET user_id = :id").bindparams(id = req_id))
        conn.execute(sa.text("UPDATE starting_balances SET user_id = :id").bindparams(id = req_id))
        conn.execute(sa.text("UPDATE transactions SET user_id = :id").bindparams(id = req_id))


    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('starting_balances', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('starting_balances', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
