"""Added user_id fields

Revision ID: 46b9aca77119
Revises: 51e6bebede18
Create Date: 2026-09-17 12:56:43.235458

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46b9aca77119'
down_revision: Union[str, Sequence[str], None] = '51e6bebede18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_id', 'categories', 'users', ['user_id'], ['id'])
    op.add_column('starting_balances', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_id', 'starting_balances', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_id', 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_id', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint('fk_user_id', 'starting_balances', type_='foreignkey')
    op.drop_column('starting_balances', 'user_id')
    op.drop_constraint('fk_user_id', 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
