"""create initial tables

Revision ID: 51e6bebede18
Revises: d60f99e0be96
Create Date: 2026-08-21 12:45:14.134341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '51e6bebede18'
down_revision: Union[str, Sequence[str], None] = 'd60f99e0be96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('starting_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upi_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM month) = 1', name='chk_first_of_month'),
    sa.CheckConstraint('cash_balance >= 0 AND upi_balance >= 0', name='chk_amount_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'GUEST')", name='chk_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=4), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('linked_transfer_id', sa.Integer(), nullable=True),
    sa.Column('is_debit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            transaction_type IN (\n            'INCOME',\n            'EXPENSE',\n            'TRANSFER',\n            'ADJUSTMENT_CREDIT',\n            'ADJUSTMENT_DEBIT'\n            )\n            ", name='chk_transaction_type'),
    sa.CheckConstraint("payment_method IN ('UPI','CASH')", name='chk_payment_method'),
    sa.CheckConstraint("transaction_type <> 'EXPENSE' OR category_id IS NOT NULL", name='chk_expenses_category'),
    sa.CheckConstraint("transaction_type <> 'TRANSFER' OR category_id IS NULL", name='chk_transfer_no_category'),
    sa.CheckConstraint("transaction_type <> 'TRANSFER' OR is_debit IS NOT NULL", name='chk_transfer_debit'),
    sa.CheckConstraint("transaction_type = 'TRANSFER' OR is_debit IS NULL", name='chk_non_transfer_debit'),
    sa.CheckConstraint("transaction_type = 'TRANSFER' OR linked_transfer_id IS NULL", name='chk_transfer_link'),
    sa.CheckConstraint('amount > 0', name='chk_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_category_id'),
    sa.ForeignKeyConstraint(['linked_transfer_id'], ['transactions.id'], name='fk_linked_transaction_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('starting_balances')
    op.drop_table('categories')
    # ### end Alembic commands ###
