"""Multi user + Unique constraint fixes

Revision ID: bac8378b87ff
Revises: 46b9aca77119
Create Date: 2026-09-18 15:04:39.302446

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bac8378b87ff'
down_revision: Union[str, Sequence[str], None] = '46b9aca77119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint('uq_name_user', 'categories', ['user_id', 'name'])
    op.drop_constraint(op.f('starting_balances_month_key'), 'starting_balances', type_='unique')
    op.create_unique_constraint('uq_month_user', 'starting_balances', ['user_id', 'month'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_month_user', 'starting_balances', type_='unique')
    op.create_unique_constraint(op.f('starting_balances_month_key'), 'starting_balances', ['month'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_name_user', 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
