-- users table
-- ID : unique Id for each user, INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
-- username : unique username , VARCHAR(50), minimum 5 enforced by Pydantic models at the API endpoint
-- password_hash : hash_password, TEXT
-- role : access permissions for the user, VARCHAR(5) 
-- created_at : timestamp, TIMESTAMP WITH TIME ZONE 
-- Constraints :
-- Check if role is either admin or guest
-- username , role and password cannot be empty/null
-- username should be unique

CREATE TABLE users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL, 
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT chk_role CHECK (role IN ('ADMIN','GUEST')),
    CONSTRAINT uq_username UNIQUE (username)
);

-- categories table
-- id : category id, INT GENERATED BY DEFAULT AS IDENTITY PK
-- name : name of the category, VARCHAR(50)
-- created_at : timestamp, TIMESTAMP WITH TIME ZONE 
-- Constraints:
-- category name should be unique and not null/empty

CREATE TABLE categories(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uq_name UNIQUE (name)
);

-- starting_balances table
-- id : just an id , INT GENERATED BY DEFAULT AS IDENTITY PK
-- month : first day of the month , DATE
-- cash_balance : starting cash balance, DECIMAL(10,2)
-- upi_balance : starting UPI balance, DECIMAL(10,2)
-- created_at : timestamp, TIMESTAMP WITH TIME ZONE 
-- Constraints:
-- month, cash_balance and upi_balance cannot be null/empty. 
-- month should be unique

CREATE TABLE starting_balances(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month DATE NOT NULL,
    cash_balance DECIMAL(10,2) NOT NULL,
    upi_balance DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uq_month UNIQUE(month)
    CONSTRAINT chk_first_of_month CHECK (EXTRACT(DAY FROM month) = 1)
);

--transactions table
-- id : transaction id, INT GENERATED BY DEFAULT AS IDENTITY PK
-- transaction_date : date when the transaction was done, DATE 
-- description : explanation for the transaction, VARCHAR(300) , min (10)
-- amount : transaction amount , DECIMAL(10,2)
-- payment_method : method of transaction, VARCHAR(4)
-- transaction_type : type of the transaction VARCHAR()
-- category_id : id of the category for the transaction , INT 
-- linked_transfer_id : if the transaction is a transfer, the id of the other transaction
-- is_debit : if the transaction is a transfer, then use this to figure out which of the transaction debits, BOOLEAN 
-- created_at : timestamp, TIMESTAMP WITH TIME ZONE 
-- updated_at : timestamp, TIMESTAMP WITH TIME ZONE 
-- Constraints:
-- transaction date, description, amount , payment_method, transaction_type cannot be NULL/emtpy
-- payment_method check if it is either 'UPI' or 'CASH'
-- transaction_type check if it either 'INCOME', 'EXPENSE', 'TRANSFER', 'ADJUSTMENT_CREDIT', 'ADJUSTMENT_DEBIT'
-- Category_id foreign key referencing id in categories
-- linked_transfer_id referencing id in transactions 
-- expenses MUST have category

CREATE TABLE transactions(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date DATE NOT NULL,
    description VARCHAR(300) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_method VARCHAR(4) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    category_id INT,
    linked_transfer_id INT,
    is_debit BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT chk_payment_method CHECK (payment_method IN ('UPI','CASH')),
    CONSTRAINT chk_transaction_type CHECK (transaction_type IN ('INCOME','EXPENSE','TRANSFER','ADJUSTMENT_CREDIT','ADJUSTMENT_DEBIT')),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_linked_transaction_id FOREIGN KEY (linked_transfer_id) REFERENCES transactions(id),
    CONSTRAINT chk_expenses_category CHECK (transaction_type != 'EXPENSE' OR category_id is NOT NULL),
    CONSTRAINT chk_transfer_link CHECK (transaction_type = 'TRANSFER' OR linked_transfer_id is NULL),
    CONSTRAINT chk_transfer_debit CHECK (transaction_type != 'TRANSFER' OR is_debit is NOT NULL),
    CONSTRAINT chk_non_transfer_debit CHECK(transaction_type = 'TRANSFER' OR is_debit IS NULL), 
    CONSTRAINT chk_amount_positive CHECK(amount > 0)
);

-- Seeding categories
-- Footwear, Clothing, Entertainment, Academics, Food, Transport

INSERT INTO categories(name) VALUES
    ('Food'),
    ('Transport'),
    ('Entertainment'),
    ('Academics'),
    ('Clothing'),
    ('Footwear');
